import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
sum=np.sum(a)
product=np.prod(a)
mean=np.mean(a)
standard_deviation=np.std(a)
variance=np.var(a)
minimum=np.min(a)
maximum=np.max(a)
minimum_index=np.argmin(a)
maximum_index=np.argmax(a)
median=np.median(a)
print("a :",a)
print("sum :",sum)
print("product :",product)
print("mean :",mean)
print("standard_deviation :",standard_deviation)
print("variance :",variance)
print("minimum :",minimum)
print("maximum :",maximum)
print("minimum index :",minimum_index)
print("maximum-index :",maximum_index)
print("median :",median)