import numpy as np
x1 = np.array(['AI&DS', 'CSE', 'IT', 'MECH', 'EEE'], dtype=np.str)
x2 = np.array(['AI&DS', 'AGRI', 'IT', 'MECH', 'ECE'], dtype=np.str)
print("\nArray1:")
print(x1)
print("Array2:")
print(x2)
print("\nEqual ")
r = np.char.equal(x1, x2)
print(r)
print("\nNot equal")
r = np.char.not_equal(x1, x2)
print(r)
print("\nLess equal ")
r = np.char.less_equal(x1, x2)
print(r)
print("\nGreater equal ")
r = np.char.greater_equal(x1, x2)
print(r)
print("\nLess ")
r = np.char.less(x1, x2)
print(r)